CREATE DATABASE test;

CREATE TABLE `test`.`user` ( `uid` INT UNSIGNED NOT NULL AUTO_INCREMENT , `credit` INT NOT NULL DEFAULT '0' , `super` INT NOT NULL DEFAULT '0' , `name` VARCHAR(128) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL UNIQUE , PRIMARY KEY (`uid`, `name`) ) ENGINE = InnoDB;

CREATE TABLE `test`.`opinion` ( `oid` INT UNSIGNED NOT NULL AUTO_INCREMENT , `uid` INT UNSIGNED NOT NULL , `eid` INT UNSIGNED NOT NULL , `opinion` INT NOT NULL , PRIMARY KEY (`oid`)) ENGINE = InnoDB;

CREATE TABLE `test`.`comment` ( `cid` INT UNSIGNED NOT NULL AUTO_INCREMENT , `uid` INT UNSIGNED NOT NULL , `eid` INT UNSIGNED NOT NULL , `time` INT NOT NULL , `comment` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL , PRIMARY KEY (`cid`)) ENGINE = InnoDB;

CREATE TABLE `test`.`event` ( `eid` INT UNSIGNED NOT NULL AUTO_INCREMENT , `uid` INT UNSIGNED NOT NULL , `lat` FLOAT NOT NULL , `lon` FLOAT NOT NULL , `date` INT NOT NULL , `status` INT NOT NULL , `agree` INT NOT NULL DEFAULT '0', `disagree` INT NOT NULL DEFAULT '0' , `description` TEXT NOT NULL , `title` TEXT NOT NULL , PRIMARY KEY (`eid`)) ENGINE = InnoDB;
